name: Test01
on: push

jobs:
  test-job:
    name: My Job1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3 
      run: |
        python -m pip install --upgrade pip;
        pip3 install -r requirements.txt;
        python3 server.py;