name: Test01
on: push

jobs:
  test-job:
    name: My Job1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: first 
      run: |
        pip3 install -r requirements.txt
    - name: server
      run: |
        python3 server.py > log.txt 2>&1 &
    - name: test
      run: |
        pytest